// flow-typed signature: dec8a36277b8247b86ab34ce159ab231
// flow-typed version: <<STUB>>/eslint-config-hubspot_v^6.2.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-config-hubspot'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-config-hubspot' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-config-hubspot/base' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/experimental' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/rules/best-practices' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/rules/errors' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/rules/es6' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/rules/experimental' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/rules/legacy' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/rules/node' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/rules/react' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/rules/strict' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/rules/style' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/rules/variables' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/test/test-base' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/test/test-experimental' {
  declare module.exports: any;
}

declare module 'eslint-config-hubspot/test/test-react-order' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-config-hubspot/base.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/base'>;
}
declare module 'eslint-config-hubspot/experimental.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/experimental'>;
}
declare module 'eslint-config-hubspot/index' {
  declare module.exports: $Exports<'eslint-config-hubspot'>;
}
declare module 'eslint-config-hubspot/index.js' {
  declare module.exports: $Exports<'eslint-config-hubspot'>;
}
declare module 'eslint-config-hubspot/legacy.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/legacy'>;
}
declare module 'eslint-config-hubspot/rules/best-practices.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/rules/best-practices'>;
}
declare module 'eslint-config-hubspot/rules/errors.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/rules/errors'>;
}
declare module 'eslint-config-hubspot/rules/es6.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/rules/es6'>;
}
declare module 'eslint-config-hubspot/rules/experimental.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/rules/experimental'>;
}
declare module 'eslint-config-hubspot/rules/legacy.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/rules/legacy'>;
}
declare module 'eslint-config-hubspot/rules/node.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/rules/node'>;
}
declare module 'eslint-config-hubspot/rules/react.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/rules/react'>;
}
declare module 'eslint-config-hubspot/rules/strict.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/rules/strict'>;
}
declare module 'eslint-config-hubspot/rules/style.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/rules/style'>;
}
declare module 'eslint-config-hubspot/rules/variables.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/rules/variables'>;
}
declare module 'eslint-config-hubspot/test/test-base.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/test/test-base'>;
}
declare module 'eslint-config-hubspot/test/test-experimental.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/test/test-experimental'>;
}
declare module 'eslint-config-hubspot/test/test-react-order.js' {
  declare module.exports: $Exports<'eslint-config-hubspot/test/test-react-order'>;
}
