// flow-typed signature: 9a0b970b565ccafa2f9f1a40b7900f29
// flow-typed version: <<STUB>>/immutable-is_v^3.7.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'immutable-is'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'immutable-is' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'immutable-is/dist/immutable-is' {
  declare module.exports: any;
}

// Filename aliases
declare module 'immutable-is/dist/immutable-is.js' {
  declare module.exports: $Exports<'immutable-is/dist/immutable-is'>;
}
