// flow-typed signature: b39ffb3ceccfa2a2ac08e424b82a2715
// flow-typed version: <<STUB>>/jest-cli_v^12.1.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-cli'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-cli' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-cli/bin/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/src/cli/getJest' {
  declare module.exports: any;
}

declare module 'jest-cli/src/cli/index' {
  declare module.exports: any;
}

declare module 'jest-cli/src/cli/processArgs' {
  declare module.exports: any;
}

declare module 'jest-cli/src/config/defaults' {
  declare module.exports: any;
}

declare module 'jest-cli/src/config/loadFromFile' {
  declare module.exports: any;
}

declare module 'jest-cli/src/config/loadFromPackage' {
  declare module.exports: any;
}

declare module 'jest-cli/src/config/normalize' {
  declare module.exports: any;
}

declare module 'jest-cli/src/config/read' {
  declare module.exports: any;
}

declare module 'jest-cli/src/Console' {
  declare module.exports: any;
}

declare module 'jest-cli/src/constants' {
  declare module.exports: any;
}

declare module 'jest-cli/src/CoverageCollector' {
  declare module.exports: any;
}

declare module 'jest-cli/src/IstanbulCollector' {
  declare module.exports: any;
}

declare module 'jest-cli/src/jest' {
  declare module.exports: any;
}

declare module 'jest-cli/src/lib/createHasteMap' {
  declare module.exports: any;
}

declare module 'jest-cli/src/lib/createResolver' {
  declare module.exports: any;
}

declare module 'jest-cli/src/lib/formatTestResults' {
  declare module.exports: any;
}

declare module 'jest-cli/src/lib/promisify' {
  declare module.exports: any;
}

declare module 'jest-cli/src/lib/transform' {
  declare module.exports: any;
}

declare module 'jest-cli/src/NullConsole' {
  declare module.exports: any;
}

declare module 'jest-cli/src/reporters/DefaultTestReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/src/reporters/IstanbulTestReporter' {
  declare module.exports: any;
}

declare module 'jest-cli/src/reporters/VerboseLogger' {
  declare module.exports: any;
}

declare module 'jest-cli/src/Runtime/Runtime' {
  declare module.exports: any;
}

declare module 'jest-cli/src/Test' {
  declare module.exports: any;
}

declare module 'jest-cli/src/TestRunner' {
  declare module.exports: any;
}

declare module 'jest-cli/src/TestWorker' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-cli/bin/jest.js' {
  declare module.exports: $Exports<'jest-cli/bin/jest'>;
}
declare module 'jest-cli/src/cli/getJest.js' {
  declare module.exports: $Exports<'jest-cli/src/cli/getJest'>;
}
declare module 'jest-cli/src/cli/index.js' {
  declare module.exports: $Exports<'jest-cli/src/cli/index'>;
}
declare module 'jest-cli/src/cli/processArgs.js' {
  declare module.exports: $Exports<'jest-cli/src/cli/processArgs'>;
}
declare module 'jest-cli/src/config/defaults.js' {
  declare module.exports: $Exports<'jest-cli/src/config/defaults'>;
}
declare module 'jest-cli/src/config/loadFromFile.js' {
  declare module.exports: $Exports<'jest-cli/src/config/loadFromFile'>;
}
declare module 'jest-cli/src/config/loadFromPackage.js' {
  declare module.exports: $Exports<'jest-cli/src/config/loadFromPackage'>;
}
declare module 'jest-cli/src/config/normalize.js' {
  declare module.exports: $Exports<'jest-cli/src/config/normalize'>;
}
declare module 'jest-cli/src/config/read.js' {
  declare module.exports: $Exports<'jest-cli/src/config/read'>;
}
declare module 'jest-cli/src/Console.js' {
  declare module.exports: $Exports<'jest-cli/src/Console'>;
}
declare module 'jest-cli/src/constants.js' {
  declare module.exports: $Exports<'jest-cli/src/constants'>;
}
declare module 'jest-cli/src/CoverageCollector.js' {
  declare module.exports: $Exports<'jest-cli/src/CoverageCollector'>;
}
declare module 'jest-cli/src/IstanbulCollector.js' {
  declare module.exports: $Exports<'jest-cli/src/IstanbulCollector'>;
}
declare module 'jest-cli/src/jest.js' {
  declare module.exports: $Exports<'jest-cli/src/jest'>;
}
declare module 'jest-cli/src/lib/createHasteMap.js' {
  declare module.exports: $Exports<'jest-cli/src/lib/createHasteMap'>;
}
declare module 'jest-cli/src/lib/createResolver.js' {
  declare module.exports: $Exports<'jest-cli/src/lib/createResolver'>;
}
declare module 'jest-cli/src/lib/formatTestResults.js' {
  declare module.exports: $Exports<'jest-cli/src/lib/formatTestResults'>;
}
declare module 'jest-cli/src/lib/promisify.js' {
  declare module.exports: $Exports<'jest-cli/src/lib/promisify'>;
}
declare module 'jest-cli/src/lib/transform.js' {
  declare module.exports: $Exports<'jest-cli/src/lib/transform'>;
}
declare module 'jest-cli/src/NullConsole.js' {
  declare module.exports: $Exports<'jest-cli/src/NullConsole'>;
}
declare module 'jest-cli/src/reporters/DefaultTestReporter.js' {
  declare module.exports: $Exports<'jest-cli/src/reporters/DefaultTestReporter'>;
}
declare module 'jest-cli/src/reporters/IstanbulTestReporter.js' {
  declare module.exports: $Exports<'jest-cli/src/reporters/IstanbulTestReporter'>;
}
declare module 'jest-cli/src/reporters/VerboseLogger.js' {
  declare module.exports: $Exports<'jest-cli/src/reporters/VerboseLogger'>;
}
declare module 'jest-cli/src/Runtime/Runtime.js' {
  declare module.exports: $Exports<'jest-cli/src/Runtime/Runtime'>;
}
declare module 'jest-cli/src/Test.js' {
  declare module.exports: $Exports<'jest-cli/src/Test'>;
}
declare module 'jest-cli/src/TestRunner.js' {
  declare module.exports: $Exports<'jest-cli/src/TestRunner'>;
}
declare module 'jest-cli/src/TestWorker.js' {
  declare module.exports: $Exports<'jest-cli/src/TestWorker'>;
}
